### ISSUE TITLE
specified values are set as defaults

### ISSUE THREAD

**Issue by Dynom** [Pimmr/config#2]
When specifying a flag, the value is used in the `default` help tooltip, to reproduce:
```sh
./app --db-url="foo" -h
  ..
  -db-url value, DB_URL=value (string)
        postgres connection string or URL (default "foo")
  ..
```

**Comment by yazgazan** [comment]
@Dynom fixed by https://github.com/Pimmr/config/pull/1/commits/babbecc95550c45bd224eb8dfca27935ae7b2e99
