### ISSUE TITLE
Let boolean flags default to true when specified without value

### ISSUE THREAD

**Issue by Dynom** [Pimmr/config#3]
Boolean flags should default to true when specified without value. For example the following should set the parameter `force` to `true`:

```sh
$ ./app --force
```

Currently you get an error saying: `flag needs an argument: -force`.

**Comment by yazgazan** [comment]
@Dynom Fixed by https://github.com/Pimmr/config/pull/1/commits/0834f79a74235cc11e8bbc21b42fd8bc827dd4ce
